[WIP] [MIN-49] Create load data from DVC version step
fuzzylabs/MindGPT pull request #32
Opened 2023-07-17 12:25 UTC by Christopher-Norman

This PR adds the step to load in the validated data into the embedding pipeline from a specific DVC version.

2023-07-19 15:20 UTC, osw282 requested changes
Just one mistake on the doc string, everything else looks good. 🔥

2023-07-19 15:20 UTC, osw282 commented on pipelines/data_embedding_pipeline/data_embedding_pipeline.py
> +        load_data: A ZenML step which embeds the text data into vectors and pushes to the vector database.
I think there is a mistake here. Should `load_data` have the first description and `embed_data` have the second?

2023-07-19 15:32 UTC, osw282 approved these changes
LGTM! 🛸

2023-07-20 08:30 UTC, KirsoppJ approved these changes
LGTM

2023-07-20 08:36 UTC, JonoCX approved these changes

2023-07-20 08:44 UTC, merged