[WIP][MIN-84] Implement data chunking
fuzzylabs/MindGPT pull request #49
Opened 2023-08-03 10:55 UTC by dudeperf3ct

We want to implement data chunking in the data embedding pipeline, prior to the embedding.

Data chunking involves splitting the text using two parameters
- `chunk_size`: What is the maximum number of characters allowed in a chunk
- `chunk_overlap`: How many characters should be overlapped between the chunks

2023-08-03 14:04 UTC, JonoCX requested changes
Mostly looking great. 

I've left some questions in the `TextSplitter` class, mostly because it's not the most straight forward to follow. My advice would be to sign post functionality with more descriptive variable names, comments, and splitting up functionality into concise (+ descriptive) blocks

2023-08-03 14:04 UTC, JonoCX commented on utils/text_splitter.py
> +        return None
Nit `return text if text else None`

2023-08-03 14:04 UTC, JonoCX commented on utils/text_splitter.py
> +                total + _len + (separator_len if len(current_doc) > 0 else 0)
Nit: this calculated twice so could be variable?

2023-08-03 14:04 UTC, JonoCX commented on utils/text_splitter.py
> +        docs = []
Typing to be consistent with the typing below?

2023-08-03 14:04 UTC, JonoCX commented on utils/text_splitter.py
> +                    print(
logger or do we need this output?

2023-08-03 14:04 UTC, JonoCX commented on utils/text_splitter.py
> +        # Get appropriate separator to use
Possible to separate out this function a little, for readability and functionality?

2023-08-03 14:04 UTC, JonoCX commented on utils/text_splitter.py
> +        if _good_splits:
It's possible for this to return no splits? What should we do in that case?

2023-08-03 14:04 UTC, JonoCX commented on utils/text_splitter.py
> +        for s in splits:
Nit: single letter variable

2023-08-03 14:04 UTC, JonoCX commented on utils/text_splitter.py
> +        for d in splits:
Nit: single letter variable

2023-08-03 14:04 UTC, JonoCX commented on utils/text_splitter.py
> +        for i, _s in enumerate(separators):
I'm slightly confused by this logic, what is it that we're trying to do here? 

My interpretation:
if the currently pointed to separator isn't an empty string, then set the separator variable to its value - break.
otherwise, search in the text for an empty string and if there is an empty string, then set the separator parameter to that and create a set of new parameters?

2023-08-03 14:07 UTC, dudeperf3ct commented on utils/text_splitter.py
> +        for i, _s in enumerate(separators):
In addition to above  we have a list of separators `""` being one of them, so first `if` works only for `""` separator else all other separator go to second `if`.  Here we maintain a separate list of separators and there's a recursion using this new list of separators in function `recursively_merge_and_split` on line  141 to perform split until we find a good split using all different separators.

Using the selected separator we split the text and then recursively merge until we don't exceed the `chunk_size`.

2023-08-03 14:13 UTC, dudeperf3ct commented on utils/text_splitter.py
> +        if _good_splits:
This is for the final chunk if there's anything left in the `_good_splits`, it appends to the `final_chunks`, an edge case.

2023-08-03 14:16 UTC, dudeperf3ct commented on utils/text_splitter.py
> +                    print(
It's a warning, added a logger for the same.

2023-08-03 14:34 UTC, dudeperf3ct commented on utils/text_splitter.py
> +                total + _len + (separator_len if len(current_doc) > 0 else 0)
In second place, it's in while loop where the length of current_doc changes hence we cannot use the same variable in second place. But I have added a variable for clarity in first place.

2023-08-04 06:32 UTC, dudeperf3ct commented on utils/text_splitter.py
> +        # Get appropriate separator to use
Created separate function and added comments for readability.

2023-08-04 10:02 UTC, JonoCX approved these changes
LGTM - nice one 🦕

2023-08-04 12:25 UTC, osw282 approved these changes
Nice work Shubham, LGTM! 🛸

2023-08-04 13:07 UTC, merged