[WIP] [MIN-76] Implement a metric database
fuzzylabs/MindGPT pull request #50
Opened 2023-08-03 12:58 UTC by osw282

2023-08-04 14:54 UTC, JonoCX approved these changes
LGTM! Nice work Oscar 🦖

2023-08-04 14:54 UTC, JonoCX commented on README.md
> +To run the monitoring service on k8s, `matcha provision` must be run before hand. We will need to build and push the metric service application to ACR. This image will be used by Kubernetes deploymen
Before hand -> beforehand

2023-08-04 14:54 UTC, JonoCX commented on README.md
> +Finally, once the pod is running, we verify that our monitoring service is working. The command below should provide an IP address for the metric service interface.
Spacing?

2023-08-04 14:54 UTC, JonoCX commented on README.md
> +kubectl get svc monitoring-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}
The quote isn't closed

2023-08-04 14:54 UTC, JonoCX commented on README.md
> +Hello world from the metric service.%
%?

2023-08-04 15:18 UTC, osw282 commented on README.md
> +Finally, once the pod is running, we verify that our monitoring service is working. The command below should provide an IP address for the metric service interface.
Like removing the space?

2023-08-07 09:04 UTC, d-lowl requested changes
I suppose we can simplify the instructions a bit, by moving configuration to docker-compose itself. Other than that, looks good

2023-08-07 09:04 UTC, d-lowl commented on README.md
> +ENV DB_HOST=metric-db
Why can't this be set by default?

2023-08-07 09:04 UTC, d-lowl commented on monitoring/metric_service/Dockerfile
> +# For the below ENV DB_HOST, change value to "metric-db" if running locally using docker-compose
Can we not set this in the docker compose itself?

2023-08-07 09:12 UTC, osw282 commented on README.md
> +ENV DB_HOST=metric-db
Running the metric service and the database locally with docker compose uses two containers, I don't think metric service container can reach the database container using localhost. I might be wrong tho.

2023-08-07 09:33 UTC, d-lowl commented on README.md
> +ENV DB_HOST=metric-db
Well, setting it in docker-compose does the trick

2023-08-07 09:34 UTC, d-lowl approved these changes

2023-08-07 09:38 UTC, merged