[MIN-75] Add function to post LLM responses to metric service from Streamlit app
fuzzylabs/MindGPT pull request #52
Opened 2023-08-07 12:59 UTC by osw282

This PR implements

2023-08-07 14:22 UTC, JonoCX requested changes
Nice! See comments 🦖

2023-08-07 14:22 UTC, JonoCX commented on app/app.py
> +    return result.text
Could just return the `result` here, rather than an ambiguous string? Then later log the `status_code` and `text`

2023-08-07 14:22 UTC, JonoCX commented on app/app.py
> +                logging.info("Metric service endpoint is None, monitoring is disabled.")
This is probably a `logging.warn` instead of `info`

2023-08-08 10:36 UTC, JonoCX approved these changes
LGTM! 🦖

2023-08-08 11:02 UTC, dudeperf3ct requested changes
Almost there, suggested changes regarding a docstring mismatch and new line for readability.

2023-08-08 11:02 UTC, dudeperf3ct commented on app/app.py
> +        Optional[str]: the url endpoint if it exists and is valid, None otherwise.
Docstring mismatch

2023-08-08 11:02 UTC, dudeperf3ct commented on app/app.py
>              prediction_endpoint = _get_prediction_endpoint()
A new line just to separate for readability.

2023-08-09 10:56 UTC, osw282 commented on app/app.py
> +        Optional[str]: the url endpoint if it exists and is valid, None otherwise.
Not sure where.

2023-08-09 11:03 UTC, dudeperf3ct commented on app/app.py
> +        Optional[str]: the url endpoint if it exists and is valid, None otherwise.
`Optional[str]` should be `str`.

2023-08-09 11:07 UTC, dudeperf3ct approved these changes
LGTM

2023-08-09 11:08 UTC, merged